"""empty message

Revision ID: 878b3431ef3e
Revises: 
Create Date: 2024-07-11 19:45:43.060853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878b3431ef3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('embed_link', sa.String(length=255), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('tracks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_reviews_album_id_albums')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reviews_member_id_members')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('members')
    op.drop_table('albums')
    # ### end Alembic commands ###
